knp_paginator:
    page_range: 10                     # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        # pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig # bootstrap 3 sliding pagination controls template
        pagination: MWSimpleAdminCrudBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig # bootstrap 3 sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: MWSimpleAdminCrudBundle:Menu:knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

#Los child son índices no deben ser iguales, aquí se agregan y configuran los item del menu.
#Permite configurar el nombre, url, id, icono, roles a quien visualiza, si tiene submenu se puede agregar.
mw_simple_admin_crud:
    setting: { site_name: Administrator Web, fos_user: false } # Default: site_name: AdminCrud, fos_user: false
    menu_setting: { id: side-menu, class: nav } # use id side-menu and class nav
    menu:
        child: { name: Home, url: mws_admin_crud_menu, id: home, icon: glyphicon glyphicon-home }
        dropdown:  
           name: dropdown
           url: null
           id: dropdown
           subMenu:
               pages: { name: Pages, url: page, id: pages, icon: glyphicon glyphicon-home }
               posts: { name: Posts, url: post, id: posts, icon: glyphicon glyphicon-home }
                #    roles: ['ROLE_ADMIN']
        #    roles: ['ROLE_USER']
        #child3: { name: Usuarios, url: admin_usuario, id: usuario, roles: ['ROLE_SUPERADMIN'], icon: glyphicon glyphicon-user }

vich_uploader:
    db_driver: orm
    mappings:
        # test_image:
        #     uri_prefix:         /images/test
        #     upload_destination: %kernel.root_dir%/../web/images/test
        #     namer:              vich_uploader.namer_origname
        #     inject_on_load:     false
        #     delete_on_update:   true
        #     delete_on_remove:   true
        imagen_image:
            uri_prefix:         /images/image
            upload_destination: '%kernel.root_dir%/../web/images/image'
            namer:              vich_uploader.namer_uniqid
            delete_on_update:   true
            delete_on_remove:   true
            inject_on_load:     true

# fos_user:
#     db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
#     firewall_name: main
#     user_class: Sistema\UserBundle\Entity\User
#     from_email:
#         address: "%mailer_user%"
#         sender_name: "%mailer_user%"

    # registration:
    #     confirmation:
    #         enabled: true

# stof_doctrine_extensions:
#     default_locale: es_AR
#     orm:
#         default:
#             # tree: true
#             timestampable: true # not needed: listeners are not enabled by default

liip_imagine:
    filter_sets:
        thumb_noticias:
            quality: 75
            filters:
                thumbnail: { size: [420, 200], mode: inset }
